language: cpp
sudo: false
compiler:
  - gcc
  - clang
addons: &addons
  apt:
    packages: &packages
      - g++-4.9
      - gcc-4.9
      - clang-3.6
      - libstdc++-4.9-dev
      - swig
      - python
      - qtbase5-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
      - ubuntu-sdk-team
env:
  - PARAM_THREADS="--enable-threads --with-python --with-qt5 --with-working-c-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--enable-threads --with-python --with-qt5 --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--disable-threads --with-python --with-qt5 --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--enable-threads --with-python --with-qt5 --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--disable-threads --with-python --with-qt5 --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
before_install:
  - lsb_release -a
before_script:
  - sh ./scripts/fix-timestamps.sh
  - mkdir objdir
  - cd objdir
script: ../configure $PARAM_THREADS
  CPPFLAGS="-U_GLIBCXX_USE_FLOAT128"
  CXXFLAGS="$CXXFLAGS"
  SWIG_FLAGS="$SWIG_FLAGS"
  && make
  && make check
after_failure:
  - cat config.log
  - cat tests/testsuite.log
branches:
  only:
    - master
notifications:
  recipients:
    - vhaisman@gmail.com
  email:
    on_success: always
    on_failure: always
