language: cpp
sudo: false
compiler:
  - gcc
  - clang
env:
  - PARAM_THREADS="--enable-threads --with-python --with-qt5 --with-working-c-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--enable-threads --with-python --with-qt5 --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--disable-threads --with-python --with-qt5 --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--enable-threads --with-python --with-qt5 --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--disable-threads --with-python --with-qt5 --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS="" QT=qtbase5-dev
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-working-locale --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--enable-threads --with-python --with-qt --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
  - PARAM_THREADS="--disable-threads --with-python --with-qt --with-iconv --with-wchar_t-support --enable-unit-tests"
    CXXFLAGS="" SWIG_FLAGS=""
before_install:
  - lsb_release -a
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository --yes
    'deb http://ppa.launchpad.net/canonical-x/x-staging/ubuntu precise main'
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test/ubuntu
  - if [ ! -z "$QT" ] ; then
      sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ;
    fi
  - sudo add-apt-repository --yes
    'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main'
  - sudo apt-get update -qq
  - sudo apt-get install -q
    gcc-4.8
    g++-4.8
    libstdc++-4.8-dev
    llvm-3.5
    clang-3.5
    swig
    python
  - if [ ! -z "$QT" ] ; then
      sudo apt-get install -q $QT ;
    fi
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40
    --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - sudo update-alternatives --config gcc
before_script:
  - sh ./scripts/fix-timestamps.sh
  - mkdir objdir
  - cd objdir
script: ../configure $PARAM_THREADS
  CPPFLAGS="-U_GLIBCXX_USE_FLOAT128"
  CXXFLAGS="$CXXFLAGS"
  SWIG_FLAGS="$SWIG_FLAGS"
  && make
  && make check
after_failure:
  - cat config.log
  - cat tests/testsuite.log
branches:
  only:
    - master
notifications:
  recipients:
    - vhaisman@gmail.com
  email:
    on_success: always
    on_failure: always
